# $FreeBSD$

PORTNAME=	pointcloud
PORTVERSION=	1.0
CATEGORIES=	databases

MAINTAINER=	gustafson.erik@gmail.com
COMMENT=	Pointcloud extenstion for PostgresSQL

USE_GITHUB=	yes
GH_ACCOUNT=	pramsey
GH_PROJECT=	pointcloud
GH_TAGNAME=	4c4bb5d

WRKSRC=		${WRKDIR}/pramsey-${PORTNAME}-${GH_TAGNAME}

USE_AUTOTOOLS=	autoconf
USES=		gmake

.include <bsd.port.mk>
